# Generated by Django 5.0.7 on 2024-07-18 11:23

from django.db import migrations, models

import task_manager.models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0002_category_created_by_category_name_task_assigned_to_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[(0, "LOW"), (1, "MEDIUM"), (2, "HIGH")], default=task_manager.models.TaskPriority["MEDIUM"]
            ),
        ),
    ]
