# Generated by Django 5.0.7 on 2024-07-18 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0004_task_completed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="created_by",
            new_name="creator",
        ),
    ]
