# Generated by Django 5.0.7 on 2024-08-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0005_rename_created_by_category_creator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="body",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
